export const AUTHENTICATED = 'AUTHENTICATED';
export const PATIENT_DETAILS_SUCCESS = 'PATIENT_DETAILS_SUCCESS';
export const NEW_APPT_REQUEST_SUCCESS = 'NEW_APPT_REQUEST_SUCCESS';
export const APPT_CANCELLATION_SUCESS = 'APPT_CANCELLATION_SUCESS';
